### ISSUE TITLE
Access job_id?

### ISSUE THREAD

**Issue by rosscdh** [mattupstate/flask-rq#14]
Hi thanks for the great lib.

Quick question is there currently a way to access the current_job? to acquire the job.id al la: http://python-rq.org/docs/jobs/

Thanks in advance

**Comment by clemsos** [comment]
This is needed !

**Comment by jonafato** [comment]
Is this referring to the `get_current_job` function? This works the same way as using RQ without Flask-RQ, e.g.

```python
from flask_rq import job
from rq import get_current_job


@job
def add(x, y):
    result = x + y
    print('Result of job {}: {}'.format(get_current_job().id, result))
    return result
```
Note that this function is [currently broken](https://github.com/nvie/rq/issues/479) in RQ, so you'll need to be on version 0.4.6 until that's fixed.

**Comment by rkubik** [comment]
Had the same issue, after downgrading to 0.4.6 it works perfectly.

    rq==0.4.6
    flask-rq==0.2

**Comment by joostdevries** [comment]
I assume this can be closed. Since RQ offers this function and it doesn't need any references to connection/queue, there's no need to implement it in flask-rq IMO.
