### ISSUE TITLE
AttributeError: 'RQ' object has no attribute 'job'

### ISSUE THREAD

**Issue by thatarchguy** [mattupstate/flask-rq#18]
I've been getting these errors in my code trying to get this plugin to work. Then I tried on your examples and I'm running into the same issue.

```
(env)nuke@arch (~/flask-rq/example)[master*] $: python run.py 
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from app import app
  File "/home/nuke/flask-rq/example/app.py", line 21, in <module>
    @rq.job
AttributeError: 'RQ' object has no attribute 'job'
```

```
(env)nuke@arch (~/flask-rq/example)[master*] $: python app.py
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    @rq.job
AttributeError: 'RQ' object has no attribute 'job'
```

**Comment by dipankar** [comment]
Looks like the documentation is not in sync with whats actually happening, so you need to import job seperately as its not a part of RQ.

from flask.ext.rq import RQ,job
@job
def your_function():

Hope this helps!

**Comment by thatarchguy** [comment]
Thank you.

I've since moved over to python-rq and haven't had any issues.
This project seems to be abandoned anyways.
